# Generated by Django 4.1.4 on 2022-12-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
