# Generated by Django 4.1.4 on 2022-12-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_category_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
