# Generated by Django 4.1.4 on 2022-12-26 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_order_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.order'),
        ),
    ]
