# Generated by Django 4.1.4 on 2022-12-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_orderitem_order_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_item_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
