# Generated by Django 4.1.4 on 2022-12-30 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_order_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_number',
        ),
    ]
