# Generated by Django 4.1.4 on 2022-12-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_transaction_transaction_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_void',
            field=models.BooleanField(default=False),
        ),
    ]
