# Generated by Django 4.1.4 on 2022-12-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_setting_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('CNY', 'CNY'), ('JPY', 'JPY'), ('NZD', 'NZD'), ('PHP', 'PHP'), ('SGD', 'SGD')], max_length=100, null=True),
        ),
    ]
