# Generated by Django 4.1.4 on 2023-01-01 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_setting_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CNY', 'CNY'), ('JPY', 'JPY'), ('PHP', 'PHP')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_id', models.CharField(max_length=100)),
                ('inventory_stocks', models.IntegerField()),
                ('inventory_created', models.DateTimeField(blank=True, null=True)),
                ('inventory_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
            },
        ),
    ]
