# Generated by Django 4.1.4 on 2023-01-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_setting_currency_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inventory_status',
            field=models.CharField(blank=True, choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], max_length=100, null=True),
        ),
    ]
