# Generated by Django 4.1.4 on 2023-01-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_inventory_inventory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_status',
            field=models.CharField(blank=True, choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], default='In Stock', max_length=100, null=True),
        ),
    ]
