# Generated by Django 4.1.4 on 2023-01-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_inventory_inventory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
