# Generated by Django 4.1.4 on 2023-01-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_category_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('user_role', models.CharField(max_length=100)),
                ('user_image', models.ImageField(blank=True, upload_to='user_images')),
                ('user_created', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
